# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "C:/Program Files (x86)/cmake/bin/cmake.exe"

# The command to remove a file.
RM = "C:/Program Files (x86)/cmake/bin/cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:/StudioProjects/GamePlay-deps

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:/StudioProjects/GamePlay-deps

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	"C:/Program Files (x86)/cmake/bin/cpack.exe" --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:/Program Files (x86)/cmake/bin/cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:/Program Files (x86)/cmake/bin/cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	"C:/Program Files (x86)/cmake/bin/cpack.exe" --config ./CPackSourceConfig.cmake C:/StudioProjects/GamePlay-deps/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:/Program Files (x86)/cmake/bin/cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:/Program Files (x86)/cmake/bin/cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:/Program Files (x86)/cmake/bin/cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:/Program Files (x86)/cmake/bin/cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:/Program Files (x86)/cmake/bin/cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:/Program Files (x86)/cmake/bin/cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:/StudioProjects/GamePlay-deps/CMakeFiles C:/StudioProjects/GamePlay-deps/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:/StudioProjects/GamePlay-deps/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gameplay-deps

# Build rule for target.
gameplay-deps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gameplay-deps
.PHONY : gameplay-deps

# fast build rule for target.
gameplay-deps/fast:
	$(MAKE) -f CMakeFiles/gameplay-deps.dir/build.make CMakeFiles/gameplay-deps.dir/build
.PHONY : gameplay-deps/fast

#=============================================================================
# Target rules for targets named json

# Build rule for target.
json: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 json
.PHONY : json

# fast build rule for target.
json/fast:
	$(MAKE) -f libjson-7.6.1/_internal/Source/CMakeFiles/json.dir/build.make libjson-7.6.1/_internal/Source/CMakeFiles/json.dir/build
.PHONY : json/fast

#=============================================================================
# Target rules for targets named DATA_COPY

# Build rule for target.
DATA_COPY: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DATA_COPY
.PHONY : DATA_COPY

# fast build rule for target.
DATA_COPY/fast:
	$(MAKE) -f tinyxml2-2.1.0/CMakeFiles/DATA_COPY.dir/build.make tinyxml2-2.1.0/CMakeFiles/DATA_COPY.dir/build
.PHONY : DATA_COPY/fast

#=============================================================================
# Target rules for targets named tinyxml2static

# Build rule for target.
tinyxml2static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyxml2static
.PHONY : tinyxml2static

# fast build rule for target.
tinyxml2static/fast:
	$(MAKE) -f tinyxml2-2.1.0/CMakeFiles/tinyxml2static.dir/build.make tinyxml2-2.1.0/CMakeFiles/tinyxml2static.dir/build
.PHONY : tinyxml2static/fast

#=============================================================================
# Target rules for targets named lua

# Build rule for target.
lua: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lua
.PHONY : lua

# fast build rule for target.
lua/fast:
	$(MAKE) -f lua-5.2.3/src/CMakeFiles/lua.dir/build.make lua-5.2.3/src/CMakeFiles/lua.dir/build
.PHONY : lua/fast

#=============================================================================
# Target rules for targets named freetype

# Build rule for target.
freetype: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freetype
.PHONY : freetype

# fast build rule for target.
freetype/fast:
	$(MAKE) -f freetype-2.4.5/CMakeFiles/freetype.dir/build.make freetype-2.4.5/CMakeFiles/freetype.dir/build
.PHONY : freetype/fast

#=============================================================================
# Target rules for targets named OpenAL

# Build rule for target.
OpenAL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenAL
.PHONY : OpenAL

# fast build rule for target.
OpenAL/fast:
	$(MAKE) -f openal-1.18.2/CMakeFiles/OpenAL.dir/build.make openal-1.18.2/CMakeFiles/OpenAL.dir/build
.PHONY : OpenAL/fast

#=============================================================================
# Target rules for targets named iconv

# Build rule for target.
iconv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iconv
.PHONY : iconv

# fast build rule for target.
iconv/fast:
	$(MAKE) -f libiconv-1.15/CMakeFiles/iconv.dir/build.make libiconv-1.15/CMakeFiles/iconv.dir/build
.PHONY : iconv/fast

#=============================================================================
# Target rules for targets named zlibstatic

# Build rule for target.
zlibstatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlibstatic
.PHONY : zlibstatic

# fast build rule for target.
zlibstatic/fast:
	$(MAKE) -f zlib-1.2.8/CMakeFiles/zlibstatic.dir/build.make zlib-1.2.8/CMakeFiles/zlibstatic.dir/build
.PHONY : zlibstatic/fast

#=============================================================================
# Target rules for targets named png_static

# Build rule for target.
png_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 png_static
.PHONY : png_static

# fast build rule for target.
png_static/fast:
	$(MAKE) -f png-1.6.15/CMakeFiles/png_static.dir/build.make png-1.6.15/CMakeFiles/png_static.dir/build
.PHONY : png_static/fast

#=============================================================================
# Target rules for targets named ogg

# Build rule for target.
ogg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ogg
.PHONY : ogg

# fast build rule for target.
ogg/fast:
	$(MAKE) -f ogg-1.3.2/CMakeFiles/ogg.dir/build.make ogg-1.3.2/CMakeFiles/ogg.dir/build
.PHONY : ogg/fast

#=============================================================================
# Target rules for targets named vorbis

# Build rule for target.
vorbis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vorbis
.PHONY : vorbis

# fast build rule for target.
vorbis/fast:
	$(MAKE) -f vorbis-1.3.4/CMakeFiles/vorbis.dir/build.make vorbis-1.3.4/CMakeFiles/vorbis.dir/build
.PHONY : vorbis/fast

#=============================================================================
# Target rules for targets named vorbisfile

# Build rule for target.
vorbisfile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vorbisfile
.PHONY : vorbisfile

# fast build rule for target.
vorbisfile/fast:
	$(MAKE) -f vorbis-1.3.4/CMakeFiles/vorbisfile.dir/build.make vorbis-1.3.4/CMakeFiles/vorbisfile.dir/build
.PHONY : vorbisfile/fast

#=============================================================================
# Target rules for targets named vorbisenc

# Build rule for target.
vorbisenc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vorbisenc
.PHONY : vorbisenc

# fast build rule for target.
vorbisenc/fast:
	$(MAKE) -f vorbis-1.3.4/CMakeFiles/vorbisenc.dir/build.make vorbis-1.3.4/CMakeFiles/vorbisenc.dir/build
.PHONY : vorbisenc/fast

#=============================================================================
# Target rules for targets named BulletCollision

# Build rule for target.
BulletCollision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletCollision
.PHONY : BulletCollision

# fast build rule for target.
BulletCollision/fast:
	$(MAKE) -f bullet-2.82-r2704/src/BulletCollision/CMakeFiles/BulletCollision.dir/build.make bullet-2.82-r2704/src/BulletCollision/CMakeFiles/BulletCollision.dir/build
.PHONY : BulletCollision/fast

#=============================================================================
# Target rules for targets named BulletDynamics

# Build rule for target.
BulletDynamics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletDynamics
.PHONY : BulletDynamics

# fast build rule for target.
BulletDynamics/fast:
	$(MAKE) -f bullet-2.82-r2704/src/BulletDynamics/CMakeFiles/BulletDynamics.dir/build.make bullet-2.82-r2704/src/BulletDynamics/CMakeFiles/BulletDynamics.dir/build
.PHONY : BulletDynamics/fast

#=============================================================================
# Target rules for targets named LinearMath

# Build rule for target.
LinearMath: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LinearMath
.PHONY : LinearMath

# fast build rule for target.
LinearMath/fast:
	$(MAKE) -f bullet-2.82-r2704/src/LinearMath/CMakeFiles/LinearMath.dir/build.make bullet-2.82-r2704/src/LinearMath/CMakeFiles/LinearMath.dir/build
.PHONY : LinearMath/fast

#=============================================================================
# Target rules for targets named base64

# Build rule for target.
base64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 base64
.PHONY : base64

# fast build rule for target.
base64/fast:
	$(MAKE) -f base64-1.0.0/CMakeFiles/base64.dir/build.make base64-1.0.0/CMakeFiles/base64.dir/build
.PHONY : base64/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... list_install_components"
	@echo "... gameplay-deps"
	@echo "... package"
	@echo "... install/strip"
	@echo "... package_source"
	@echo "... install"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... json"
	@echo "... DATA_COPY"
	@echo "... tinyxml2static"
	@echo "... lua"
	@echo "... freetype"
	@echo "... OpenAL"
	@echo "... iconv"
	@echo "... zlibstatic"
	@echo "... png_static"
	@echo "... ogg"
	@echo "... vorbis"
	@echo "... vorbisfile"
	@echo "... vorbisenc"
	@echo "... BulletCollision"
	@echo "... BulletDynamics"
	@echo "... LinearMath"
	@echo "... base64"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

